// ============================================================
// QUIZ DATA — 全10レッスン × 多種問題（四択・穴埋め・並び替え・ライティング・ひねり）
// ============================================================
const QUIZ_BANK = {
  l21:[
    // ── 四択 ──
    {type:"mc",diff:1,q:"「私の兄は父と同じくらい背が高い。」( ___ )に入る正しい語句は？",blank:"My brother is ___ tall ___ my father.",
     opts:["as / as","so / as","as / than","more / than"],ans:0,
     exp:"〈as＋原級＋as〜〉「〜と同じくらい…だ」。2つのasが必要。"},
    {type:"mc",diff:1,q:"「この部屋はあの部屋の2倍の大きさだ。」正しい文は？",blank:"",
     opts:["This room is twice as large as that one.","This room is more large than that twice.","This room is as twice large as that one.","This room is two times large than that."],ans:0,
     exp:"〈X times as...as〜〉「〜のX倍…だ」。2倍はtwice、half（半分）も覚えよう。"},
    {type:"mc",diff:2,q:"「〜ほど…ではない」を正しく表している文は？",blank:"",
     opts:["She is not as tall as me.","She is less tall than me.","Both A and B","A and B are both correct"],ans:3,
     exp:"〈not as[so]＋原級＋as〜〉も〈less＋原級＋than〜〉もどちらも「〜ほど…でない」を表す。"},
    {type:"mc",diff:2,q:"比較級を強調する語として正しいのは？",blank:"This house is ___ larger than mine.",
     opts:["very","much","more","mostly"],ans:1,
     exp:"比較級を強調するにはmuch/far/still/evenを使う。veryは比較級には使えない。"},
    {type:"mc",diff:3,q:"「彼の第2小説は第1作の3倍の長さだ」を正しく表すのは？",blank:"",
     opts:["His second novel is three times the length of his first one.","His second novel is three times as long as his first one.","His second novel is three times more long than his first one.","Both A and B"],ans:3,
     exp:"名詞を使って倍数を表す場合は〈X times the 名詞 of〉。asを使う場合は〈X times as 形容詞 as〉。どちらも正しい。"},
    // ── 穴埋め ──
    {type:"fill",diff:1,q:"( ___ )に入る語を書きなさい。「できるだけ早く医師を呼べ！」",
     blank:"Call the doctor ___ soon ___ possible!",
     ans:["as","as"],hint:"as ... as possible「できるだけ〜」",
     exp:"as ... as possible / as ... as one can「できるだけ〜」"},
    {type:"fill",diff:2,q:"( ___ )に入る語を書きなさい。「彼女は私より3歳年下だ」",
     blank:"She is three years ___ than me.",
     ans:["younger"],hint:"「年下」=younger",
     exp:"〈数値＋比較級＋than〜〉で差を表せる。"},
    {type:"fill",diff:2,q:"( ___ )に入る語を書きなさい。「彼はスーよりずっと大きい」",
     blank:"He is ___ larger than Sue.",
     ans:["much","far"],hint:"差を強調する副詞",
     exp:"much/far/still/even＋比較級で「はるかに〜」を表す。"},
    // ── 並び替え ──
    {type:"sort",diff:2,q:"「私はあなたと同じくらいたくさんの本を持っている」になるよう並べ替えなさい。",
     words:["I","have","as","many","books","as","you"],
     ans:"I have as many books as you",
     exp:"〈as＋形容詞/副詞＋as〜〉の語順。"},
    {type:"sort",diff:3,q:"「木はどんどん高くなっている」になるよう並べ替えなさい。",
     words:["The","tree","is","growing","taller","and","taller"],
     ans:"The tree is growing taller and taller",
     exp:"〈比較級＋and＋比較級〉「ますます〜」"},
    // ── ライティング ──
    {type:"write",diff:2,q:"次の日本語を英語にしなさい。「彼女はあのクラスで2番目に背の高い生徒だ。」",
     hint:"the second tallest ... を使う",
     model:"She is the second tallest student in that class.",
     exp:"〈the＋序数＋最上級＋単数形の名詞〉の構造。"},
    {type:"write",diff:3,q:"次の日本語を英語にしなさい。「この建物はあの建物の半分の大きさだ。」",
     hint:"half as ... as を使う",
     model:"This building is half as large[big] as that one.",
     exp:"〈half as＋原級＋as〜〉「〜の半分の…だ」"},
    // ── ひねり ──
    {type:"twist",diff:3,q:"「彼は私の父と同じくらい背が高くない。」という日本語を英語に。\n（ヒント：not as ... as を使う）",
     hint:"not as tall as を使う",
     model:"He is not as[so] tall as my father.",
     exp:"not as[so]＋原級＋as〜「〜ほど…ではない」"},
    {type:"twist",diff:3,q:"【書き換え問題】次の文を「比較級＋than any other＋単数名詞」を使って書き換えなさい。\n「Mt. Fuji is the highest mountain in Japan.」",
     hint:"higher than any other mountain を使う",
     model:"Mt. Fuji is higher than any other mountain in Japan.",
     exp:"最上級→比較級による最上級表現への書き換え。"},
  ],
  l22:[
    {type:"mc",diff:1,q:"「彼はこの学校で最も速いスプリンターだ」正しい文は？",blank:"",
     opts:["He is the fastest sprinter in this school.","He is most fast sprinter in this school.","He is the most fast sprinter in this school.","He is faster sprinter than this school."],ans:0,
     exp:"速さの最上級は fastest（-est形）。in＋範囲。"},
    {type:"mc",diff:2,q:"「〜のうちよりも大きい州はない」で正しい構造は？",blank:"___ state in the US is as large as Alaska.",
     opts:["No other","Not any","Not every","Any other"],ans:0,
     exp:"〈No (other)＋単数名詞...as[so]＋原級＋as〜〉「〜ほど…なものはない」"},
    {type:"mc",diff:2,q:"最上級を強調する語として正しいのは？",blank:"She is ___ the best singer.",
     opts:["by far","very","a lot","quite"],ans:0,
     exp:"by far/muchで最上級を強調。veryは最上級の直前にはtheをつける：the very best。"},
    {type:"mc",diff:3,q:"「そのドラマは悲劇というよりはむしろ喜劇だった」正しい文は？",blank:"",
     opts:["The drama was not so much a tragedy as a comedy.","The drama was more tragedy than comedy.","The drama was less a tragedy than a comedy.","The drama was not such a tragedy as a comedy."],ans:0,
     exp:"〈not so much A as B〉「AというよりはむしろB」"],
    {type:"fill",diff:1,q:"「アラスカはアメリカの他のどの州よりも広い」( ___ )を埋めなさい。",
     blank:"Alaska is larger than ___ other state in the United States.",
     ans:["any"],hint:"「他のどの〜よりも」",
     exp:"〈比較級＋than any other＋単数名詞〉"},
    {type:"fill",diff:2,q:"「これはこの店で最も安いコンピューターだ」( ___ )を埋めなさい。",
     blank:"This is the ___ expensive computer in this store.",
     ans:["least"],hint:"「もっとも…でない」=the least",
     exp:"〈the least＋原級〉「最も〜でない」。leastはlittleの最上級。"},
    {type:"sort",diff:2,q:"「彼女はこの国で群を抜いて最高の歌手だ」になるよう並べ替えなさい。",
     words:["She","is","by","far","the","best","singer","in","this","country"],
     ans:"She is by far the best singer in this country",
     exp:"by far＋the＋最上級で「群を抜いて〜」"},
    {type:"sort",diff:3,q:"「5万羽もの鳥がここで冬を過ごす」になるよう並べ替えなさい。",
     words:["As","many","as","fifty","thousand","birds","spend","the","winter","here"],
     ans:"As many as fifty thousand birds spend the winter here",
     exp:"〈as many as＋数詞〉「〜もの」"},
    {type:"write",diff:2,q:"「これはホテルで最も素敵な部屋の1つだ」を英語にしなさい。",
     hint:"one of the + 最上級 + 複数形",
     model:"This is one of the nicest rooms in the hotel.",
     exp:"〈one of the＋最上級＋複数形の名詞〉"},
    {type:"write",diff:3,q:"「時間ほど貴重なものはない」をNo(other)構文と比較級構文の2通りで英語にしなさい。",
     hint:"No thing is as precious as ... / Nothing is more precious than ...",
     model:"Nothing is as[so] precious as time. / Nothing is more precious than time.",
     exp:"no構文で最上級の意味を表す2つのパターン。"},
    {type:"twist",diff:3,q:"【書き換え】「No other student in this class is as tall as Henry.」を最上級を使った文に書き換えなさい。",
     hint:"the tallest student in this class",
     model:"Henry is the tallest student in this class.",
     exp:"No (other)...as[so]＋原級＋as〜 → the＋最上級への書き換え。"},
    {type:"twist",diff:3,q:"「彼女はあいかわらず元気そうに見える」を as ... as ever を使って英語にしなさい。",
     hint:"as cheerful as ever",
     model:"She looks as cheerful as ever.",
     exp:"〈as＋形容詞＋as ever〉「あいかわらず〜」"},
  ],
  l23:[
    {type:"mc",diff:1,q:"「ますます〜」を表す表現は？",blank:"The tree is growing ___.",
     opts:["taller and taller","more and more tall","the more tall","much taller"],ans:0,
     exp:"〈比較級＋and＋比較級〉「ますます〜」"},
    {type:"mc",diff:2,q:"「〜すればするほど…」を表す正しい形は？",blank:"",
     opts:["The more I study, the more I know.","More I study, more I know.","As more I study, as more I know.","The more I study, I know more."],ans:0,
     exp:"〈the＋比較級..., the＋比較級...〉「〜すればするほど…」"},
    {type:"mc",diff:2,q:"「たったの3,000円しか払わなかった」(＝only) を表す表現は？",blank:"He paid me ___ 3,000 yen.",
     opts:["no more than","no less than","not more than","not less than"],ans:0,
     exp:"〈no more than〜〉「(ほんの)〜しか」＝only"},
    {type:"mc",diff:3,q:"「休息することは働くことと同様に重要だ」正しい文は？",blank:"",
     opts:["Relaxing is no less important than working.","Relaxing is no more important than working.","Relaxing is not less important than working.","Relaxing is less important than working."],ans:0,
     exp:"〈A...no less...than B〉「〜に劣らず…だ」"},
    {type:"fill",diff:2,q:"「どんどん大きくなる」( ___ )を埋めなさい。",
     blank:"The balloon is growing bigger ___ bigger.",
     ans:["and"],hint:"比較級 + and + 比較級",
     exp:"〈比較級＋and＋比較級〉「ますます〜」"},
    {type:"fill",diff:3,q:"「2匹の子犬のうちより小さいほう」( ___ )を埋めなさい。",
     blank:"the ___ of the two puppies",
     ans:["smaller"],hint:"the + 比較級 + of the two",
     exp:"〈the＋比較級＋of the two〉「2つのうちで、より〜なほう」"},
    {type:"sort",diff:2,q:"「勉強すればするほど、より多くのことを知る」になるよう並べ替えなさい。",
     words:["The","more","I","study","the","more","I","know"],
     ans:"The more I study the more I know",
     exp:"〈the＋比較級..., the＋比較級...〉"},
    {type:"sort",diff:3,q:"「彼は失礼というよりはむしろ愚かだった」になるよう並べ替えなさい。",
     words:["His","behavior","was","more","foolish","than","rude"],
     ans:"His behavior was more foolish than rude",
     exp:"〈more B than A〉「AというよりはむしろB」"},
    {type:"write",diff:2,q:"「私は友達といる時が一番幸せだ（自分の中での比較）」を英語にしなさい。",
     hint:"happiest（theをつけない）",
     model:"I feel happiest when I'm with my friends.",
     exp:"自分の中での比較の場合、最上級にtheはつけない。"},
    {type:"write",diff:3,q:"「彼女は30,000円もの額を払ってくれた（no less than）」と「少なくとも20,000円（not less than）」をそれぞれ英語にしなさい。",
     hint:"no less than / not less than の違いに注目",
     model:"She paid me no less than 30,000 yen. / The cost will be not less than 20,000 yen.",
     exp:"no less than〜「〜ほども多く」/ not less than〜「少なくとも〜」"},
    {type:"twist",diff:3,q:"「人間はゴリラより知性において優れている」を英語にしなさい。（thanを使わない）",
     hint:"superior to を使う",
     model:"Humans are superior to gorillas in intelligence.",
     exp:"〈superior to〜〉「〜より優れている」。thanではなくtoを使うことに注意。"},
    {type:"twist",diff:3,q:"【ひねり】「雨が降っているので、ピクニックに行けない。」→「もし雨が降っていなければ、ピクニックに行けるのに。」を仮定法で英語にしなさい。",
     hint:"if it were not raining ... could go",
     model:"If it were not raining, we could go to the picnic.",
     exp:"現在の事実の反対→仮定法過去：If＋S＋were/動詞の過去形, S＋would/could..."},
  ],
  l24:[
    {type:"mc",diff:1,q:"「私にはボストンに住んでいる友人がいる」先行詞が人・主格の関係代名詞は？",blank:"I have a friend ___ lives in Boston.",
     opts:["who","which","whom","whose"],ans:0,
     exp:"who：先行詞が人、主格（関係詞節中の動詞の主語）。"},
    {type:"mc",diff:1,q:"先行詞が「物」で主格の関係代名詞は？",blank:"They live in a house ___ stands on a hill.",
     opts:["which","who","whom","whose"],ans:0,
     exp:"which：先行詞が人以外（物・動物など）。"},
    {type:"mc",diff:2,q:"所有格の関係代名詞を選びなさい。（先行詞が人）",blank:"He has a friend ___ wife is a singer.",
     opts:["whose","who's","which","that"],ans:0,
     exp:"whose：所有格の関係代名詞。先行詞が人でも物でもwhoseを使う。"},
    {type:"mc",diff:2,q:"前置詞の直後に置ける関係代名詞の組み合わせとして正しいのは？",blank:"He is the actor to ___ Ann sent a fan letter.",
     opts:["whom","who","that","which or whom"],ans:3,
     exp:"前置詞の直後（前置詞＋...）に来る場合はwhom（人）またはwhich（物）のみ使用可能。thatは使えない。"},
    {type:"mc",diff:3,q:"thatが特に好まれる先行詞はどれ？",blank:"",
     opts:["the only book","a book","some books","many books"],ans:0,
     exp:"the first, the last, the＋最上級, the same, the onlyなど特定の1つを示す修飾語を伴う場合はthatが好まれる。"},
    {type:"fill",diff:1,q:"( ___ )に入る語を書きなさい。（先行詞が人・目的格）",
     blank:"The man ___ I met on the street works at a bank.",
     ans:["whom","who","that"],hint:"目的格の関係代名詞（省略も可）",
     exp:"目的格の関係代名詞：who(m)/that（省略も可）。whomは文章体。"},
    {type:"fill",diff:2,q:"( ___ )に入る語を書きなさい。（先行詞が物・所有格）",
     blank:"I'm looking for a book ___ subject is jazz.",
     ans:["whose"],hint:"所有格",
     exp:"whose：先行詞が物でも使える所有格の関係代名詞。"},
    {type:"sort",diff:2,q:"「私が昨日買ったCDはどこですか？」になるよう並べ替えなさい。",
     words:["Where","is","the","CD","I","bought","yesterday"],
     ans:"Where is the CD I bought yesterday",
     exp:"目的格の関係代名詞thatが省略されている形。"},
    {type:"sort",diff:3,q:"「私はポケットの中にあったお金を彼に貸した」になるよう並べ替えなさい。",
     words:["I","lent","him","the","money","that","was","in","my","pocket"],
     ans:"I lent him the money that was in my pocket",
     exp:"that（主格）が先行詞the moneyを修飾している。"},
    {type:"write",diff:2,q:"「これは私が生まれた都市だ」を英語にしなさい。（前置詞を後ろに置く形と前に出す形の両方）",
     hint:"which/that I was born in / in which I was born",
     model:"This is the city (which[that]) I was born in. / This is the city in which I was born.",
     exp:"前置詞を後ろに置く形では省略可。前に出す形ではwhich/whomのみ使用可。"},
    {type:"write",diff:3,q:"「彼は今の彼でなかった10年前の人物ではない」を英語にしなさい。（thatを使う）",
     hint:"the man that he was ten years ago",
     model:"He is not the man that he was ten years ago.",
     exp:"thatが補語となっている場合（Eのケース）。"},
    {type:"twist",diff:3,q:"【ひねり】「私には姉が一人います。その姉はピアノがとても上手です。」を関係代名詞を使って1文にしなさい。",
     hint:"I have a sister who plays ... / I have a sister, who plays ...",
     model:"I have a sister who[that] plays the piano very well.",
     exp:"先行詞（a sister）を修飾する限定用法の関係代名詞節。"},
  ],
  l25:[
    {type:"mc",diff:1,q:"whatの正しい説明は？",blank:"",
     opts:["先行詞を含む関係代名詞で「〜すること[もの]」を意味する","先行詞が人のときだけ使う","先行詞が物のときだけ使う","継続用法にのみ使う"],ans:0,
     exp:"what = the thing(s) that〜。先行詞を含む関係代名詞で、先行詞なしで使う。"},
    {type:"mc",diff:2,q:"継続用法でthatを使えるか？",blank:"",
     opts:["使えない（thatは継続用法不可）","コンマがあるときは使える","先行詞が人以外のとき使える","どんな場合でも使える"],ans:0,
     exp:"thatは継続用法には使えない。継続用法にはwho/which（コンマあり）を使う。"},
    {type:"mc",diff:2,q:"前置詞を前に出すとき ( ___ ) に入るのは？",blank:"He is the actor to ___ Ann sent a fan letter.",
     opts:["whom","who","that","which"],ans:0,
     exp:"前置詞の直後は whom（人）または which（物）のみ。who・that は使えない。"},
    {type:"mc",diff:3,q:"継続用法のwhichが先行詞としてとれるものは？",blank:"",
     opts:["直前の語句・節・文の内容全体","先行詞（人）のみ","先行詞（物）のみ","直前の文全体のみ"],ans:0,
     exp:"継続用法のwhichは(a)直前の語句、(b)直前の節、(c)直前の文の内容全体を先行詞にできる。"},
    {type:"fill",diff:2,q:"「私を悩ませているのは試験の結果だ」( ___ )を埋めなさい。",
     blank:"___ worries me is the result of the exam.",
     ans:["What"],hint:"先行詞を含む関係代名詞",
     exp:"What（＝the thing that）を使って節全体が主語になる。"},
    {type:"fill",diff:2,q:"「彼はイタリア製のブラウンのスーツを着ていた」（継続用法）( ___ )を埋めなさい。",
     blank:"He wore a brown suit, ___ was made in Italy.",
     ans:["which"],hint:"継続用法のwhich",
     exp:"コンマ＋which（継続用法）。先行詞はa brown suit。"},
    {type:"sort",diff:2,q:"「私を悩ませているのは試験の結果だ」になるよう並べ替えなさい。",
     words:["What","worries","me","is","the","result","of","the","exam"],
     ans:"What worries me is the result of the exam",
     exp:"Whatが主語節を作っている。"},
    {type:"sort",diff:3,q:"「この時計はまさに私が欲しかったものだ」になるよう並べ替えなさい。",
     words:["This","watch","is","just","what","I","wanted"],
     ans:"This watch is just what I wanted",
     exp:"whatが補語節を作っている。"},
    {type:"write",diff:2,q:"「彼はチョコレートをくれた。私はすぐに食べた。」を関係代名詞の継続用法を使って1文にしなさい。",
     hint:"He gave me some chocolates, which ...",
     model:"He gave me some chocolates, which I ate at once.",
     exp:"継続用法のwhich。= He gave me some chocolates, and I ate them at once."},
    {type:"write",diff:3,q:"「私は外出中に電話してきていたロッドに電話した。」を関係代名詞の継続用法を使って英語にしなさい。",
     hint:"I telephoned Rod, who ...",
     model:"I telephoned Rod, who had called while I was out.",
     exp:"継続用法のwho。= I telephoned Rod, because he had called while I was out."},
    {type:"twist",diff:3,q:"【ひねり】「彼女は自分が見たものを信じられなかった。」をwhatを使って英語にしなさい。",
     hint:"what they saw",
     model:"She couldn't believe what she saw.",
     exp:"what = the thing that。whatの節が動詞believeの目的語になる。"},
    {type:"twist",diff:3,q:"【書き換え】「He wore a brown suit, which was made in Italy.」を接続詞を使って書き換えなさい。",
     hint:"and it was ...",
     model:"He wore a brown suit, and it was made in Italy.",
     exp:"継続用法のwhich ≒ and it（ここではa brown suitを指す）"},
  ],
  l26:[
    {type:"mc",diff:1,q:"「場所」を表す関係副詞は？",blank:"This is the hospital ___ my aunt works.",
     opts:["where","when","why","how"],ans:0,
     exp:"where：「場所」を表す副詞の役割。"},
    {type:"mc",diff:1,q:"「理由」を表す関係副詞は？",blank:"Tell me the reason ___ you look so happy.",
     opts:["why","where","when","how"],ans:0,
     exp:"why：「〜する(理由)」。先行詞はreason(s)。"},
    {type:"mc",diff:2,q:"howについて正しい説明は？",blank:"",
     opts:["先行詞なしで使い、the way howとは言えない","先行詞がwayのときだけ使う","the way howでも使える","先行詞が必要な関係副詞"],ans:0,
     exp:"how：先行詞なしで使う。×the way how → ○the way (in which) / the way that / how"},
    {type:"mc",diff:2,q:"「〜する人はだれでも」を意味する複合関係詞は？",blank:"",
     opts:["whoever","whatever","whenever","whichever"],ans:0,
     exp:"whoever「〜する人はだれでも」= no matter who"},
    {type:"mc",diff:3,q:"「place, case, situation など」も先行詞になれる関係副詞は？",blank:"",
     opts:["where","when","why","how"],ans:0,
     exp:"whereは場所以外にも場合・状況・立場などを表す語も先行詞となる。"},
    {type:"fill",diff:1,q:"「恐竜が地球上に生きていた時代があった」( ___ )を埋めなさい。",
     blank:"There was a time ___ dinosaurs lived on the earth.",
     ans:["when"],hint:"「時」を表す関係副詞",
     exp:"when：「時」を表す副詞の役割。"},
    {type:"fill",diff:2,q:"「休日には、好きな時間に起きることができる」( ___ )を埋めなさい。",
     blank:"On holidays, we can get up ___ we want to.",
     ans:["whenever"],hint:"「〜する時ならいつでも」",
     exp:"whenever「〜する時ならいつでも」"},
    {type:"sort",diff:2,q:"「それが彼がビジネスで成功したやり方だ」になるよう並べ替えなさい。",
     words:["That's","how","he","succeeded","in","business"],
     ans:"That's how he succeeded in business",
     exp:"how：「〜するやり方」先行詞なしで使う。"},
    {type:"sort",diff:3,q:"「テーブルは好きなところに置いていいですよ」になるよう並べ替えなさい。",
     words:["Put","the","table","wherever","you","like"],
     ans:"Put the table wherever you like",
     exp:"wherever「〜するところならどこでも」"},
    {type:"write",diff:2,q:"「大阪に行く時はいつも叔父を訪問する」を英語にしなさい。",
     hint:"whenever I go to Osaka",
     model:"I visit my uncle whenever I go to Osaka.",
     exp:"whenever「〜する時はいつも」"},
    {type:"write",diff:3,q:"「これが私の叔母が働いている病院だ」を関係副詞のwhereを使った文と、前置詞＋which を使った文の2通りで書きなさい。",
     hint:"where / at which",
     model:"This is the hospital where my aunt works. / This is the hospital at which my aunt works.",
     exp:"関係副詞where ＝ 前置詞＋which（前置詞は動詞worksに対応してat）"},
    {type:"twist",diff:3,q:"【ひねり】「私が大阪を訪れれば必ず叔母を訪問する」という意味の文を書きなさい。",
     hint:"whenever を使う",
     model:"I visit my aunt whenever I visit Osaka. / Whenever I visit Osaka, I visit my aunt.",
     exp:"whenever「〜するときはいつも」で副詞節を作る。"},
  ],
  l27:[
    {type:"mc",diff:1,q:"「どれほど疲れていても」を表す表現は？",blank:"___ tired she is, she always smiles.",
     opts:["However","Whatever","Whoever","Whenever"],ans:0,
     exp:"however＋形容詞/副詞＋S＋V「どれほど〜でも」= no matter how"},
    {type:"mc",diff:1,q:"「what is called」の意味は？",blank:"",
     opts:["いわゆる〜","〜するもの","現在の〜","まるで〜のように"],ans:0,
     exp:"what is called「いわゆる〜」"},
    {type:"mc",diff:2,q:"「what is more」の意味は？",blank:"",
     opts:["そのうえ","もっと何か","さらに悪いことに","それどころか"],ans:0,
     exp:"what is more「そのうえ」。⇔what is worse「さらに悪いことに」"},
    {type:"mc",diff:2,q:"「however」を「no matter〜」で言い換えると？",blank:"",
     opts:["no matter how","no matter what","no matter who","no matter which"],ans:0,
     exp:"however = no matter how。similarly: whoever=no matter who, whatever=no matter what"},
    {type:"fill",diff:2,q:"「何が起こっても、私はずっとあなたを愛している」( ___ )を埋めなさい。",
     blank:"___ happens, I will always love you.",
     ans:["Whatever"],hint:"「何が〜しようとも」",
     exp:"whatever「何が[を]〜しようとも」= no matter what"},
    {type:"fill",diff:3,q:"「これはその映画でその俳優が着ていたのと同じ上着だ」( ___ )を埋めなさい。",
     blank:"This is the same jacket ___ was worn by the actor in the movie.",
     ans:["as"],hint:"the same ... as",
     exp:"〈the same...as〉の asは関係代名詞として節の中で主語の働きをする。"},
    {type:"sort",diff:2,q:"「誰が電話してきても、私は出たくない」になるよう並べ替えなさい。",
     words:["Whoever","calls","me","I","don't","want","to","answer","the","phone"],
     ans:"Whoever calls me I don't want to answer the phone",
     exp:"whoever「だれが〜しようとも」= no matter who"},
    {type:"sort",diff:3,q:"「読書と心の関係は、運動と体の関係に等しい」になるよう並べ替えなさい。",
     words:["Reading","is","to","the","mind","what","exercising","is","to","the","body"],
     ans:"Reading is to the mind what exercising is to the body",
     exp:"A is to B what C is to D「AのBに対する関係は、CのDに対する関係に等しい」"},
    {type:"write",diff:2,q:"「この音楽はいわゆるラップというものだ」を英語にしなさい。",
     hint:"what is called",
     model:"This music is what is called \"rap.\"",
     exp:"what is called「いわゆる〜」"},
    {type:"write",diff:3,q:"「どんなに疲れていても、彼女はいつも微笑む」を however と no matter how の2通りで書きなさい。",
     hint:"However tired she is ... / No matter how tired she is ...",
     model:"However tired she is, she always smiles. / No matter how tired she is, she always smiles.",
     exp:"however = no matter howで書き換え可能。"},
    {type:"twist",diff:3,q:"【ひねり】「彼の父親が今日の彼を作り上げた」をwhat S is を使って英語にしなさい。",
     hint:"what he is today",
     model:"His father made him what he is today.",
     exp:"what S is「現在のS」"},
    {type:"twist",diff:3,q:"「私はあなたがどこへ行っても、あなたのことを思っているよ」を wherever を使って英語にしなさい。",
     hint:"wherever you go",
     model:"I'll be thinking of you wherever you go.",
     exp:"wherever「〜するところならどこでも/どこへ〜しようとも」"},
  ],
  l28:[
    {type:"mc",diff:1,q:"仮定法過去の正しい形は？（現在の事実と反対）",blank:"If he ___ ready, we ___ go.",
     opts:["were / would","is / will","had been / would","was being / could"],ans:0,
     exp:"仮定法過去：If＋S＋動詞の過去形（be動詞はwere），S＋would[could/might]＋動詞の原形。"},
    {type:"mc",diff:2,q:"仮定法過去完了の正しい形は？（過去の事実と反対）",blank:"If I ___ earlier, I ___ the train.",
     opts:["had left / would not have missed","left / would not miss","had left / would not miss","left / would not have missed"],ans:0,
     exp:"仮定法過去完了：If＋S＋had＋過去分詞，S＋would[could/might]＋have＋過去分詞。"},
    {type:"mc",diff:2,q:"仮定法でbe動詞を使うとき（主語がIやheでも）使うのは？",blank:"",
     opts:["were","was","is","be"],ans:0,
     exp:"仮定法ではbe動詞は人称・数に関係なくwereを使う（口語ではwasも可）。"},
    {type:"mc",diff:3,q:"「もし（あの時）〜だったなら、（今は）…だろうに」という混合仮定法の形は？",blank:"",
     opts:["if節=had＋過去分詞、主節=would＋原形","if節=過去形、主節=would have＋過去分詞","if節=had＋過去分詞、主節=would have＋過去分詞","if節=過去形、主節=would＋原形"],ans:0,
     exp:"if節が仮定法過去完了（過去の仮定）＋主節が仮定法過去（現在の結果）の混合形。"},
    {type:"fill",diff:1,q:"「もし大金があれば、島を買うのに」( ___ )を埋めなさい。",
     blank:"If I ___ a lot of money, I would ___ an island.",
     ans:["had","buy"],hint:"仮定法過去の形",
     exp:"仮定法過去：If＋S＋過去形，S＋would＋原形。"},
    {type:"fill",diff:2,q:"「もし10分早く出発していたら、電車に乗り遅れなかっただろう」( ___ )を埋めなさい。",
     blank:"If I had left ten minutes earlier, I ___ not have ___ the train.",
     ans:["would","missed"],hint:"仮定法過去完了の主節",
     exp:"主節：S＋would[could/might]＋have＋過去分詞"},
    {type:"sort",diff:2,q:"「もし時間とお金が十分あれば、世界中を旅するのに」になるよう並べ替えなさい。",
     words:["If","I","had","enough","time","and","money","I","would","travel","around","the","world"],
     ans:"If I had enough time and money I would travel around the world",
     exp:"仮定法過去：If＋S＋過去形，S＋would＋原形。"},
    {type:"sort",diff:3,q:"「もし彼の準備ができていれば、私たちは行くのに」になるよう並べ替えなさい。",
     words:["If","he","were","ready","we","would","go"],
     ans:"If he were ready we would go",
     exp:"仮定法過去：be動詞はwereを使う（主語がheでも）。"},
    {type:"write",diff:2,q:"「もし翼があれば、あなたのもとへ飛んでいくのに」を英語にしなさい。",
     hint:"If I had wings, I would ...",
     model:"If I had wings, I would fly to you.",
     exp:"仮定法過去：現在の事実と反対のことを表す。"},
    {type:"write",diff:3,q:"「もし彼女が10分早く出発していたら、電車に乗り遅れなかっただろう」を英語にしなさい。",
     hint:"had left / would not have missed",
     model:"If she had left ten minutes earlier, she would not have missed the train.",
     exp:"仮定法過去完了：過去の事実と反対のことを表す。"},
    {type:"twist",diff:3,q:"「試験に落ちた（過去）。だから今後悔している（現在）。」を仮定法を使って1文で表しなさい。",
     hint:"If I had studied harder then, I ... now.",
     model:"If I had studied harder then, I would not be feeling so regretful now.",
     exp:"混合仮定法：if節＝仮定法過去完了（過去の事実），主節＝仮定法過去（現在の結果）。"},
    {type:"twist",diff:3,q:"「雨が降っているのでピクニックに行けない」→「もし雨が降っていなければ、ピクニックに行けるのに」を仮定法過去で英語にしなさい。",
     hint:"If it were not raining, we could go ...",
     model:"If it were not raining, we could go to the picnic.",
     exp:"現在の事実の反対→仮定法過去。進行形の仮定法も可。"},
  ],
  l29:[
    {type:"mc",diff:1,q:"「彼女の電話番号を知っていればなあ（今現在の願望）」正しいのは？",blank:"I wish I ___ her telephone number.",
     opts:["knew","know","had known","would know"],ans:0,
     exp:"I wish＋仮定法過去「〜ならなあ」。願っている時と同時のことは過去形を使う。"},
    {type:"mc",diff:2,q:"「あのバッグを買わなければよかった（過去への後悔）」正しいのは？",blank:"I wish I ___ such an expensive bag.",
     opts:["hadn't bought","didn't buy","wouldn't buy","haven't bought"],ans:0,
     exp:"I wish＋仮定法過去完了「〜だったらなあ」。過去のことへの後悔。"},
    {type:"mc",diff:2,q:"ifの省略による倒置で正しい文は？",blank:"",
     opts:["Were I you, I would ask her.","Was I you, I would ask her.","If were I you, I would ask her.","I were you, I would ask her."],ans:0,
     exp:"ifを省略するとSVが倒置される。wereが文頭に出る形。"},
    {type:"mc",diff:3,q:"「もし〜するようなことがあれば（未来・実現可能性低）」という意味を表すのは？",blank:"If he ___ change his mind, he would call me.",
     opts:["should","would","could","were to"],ans:0,
     exp:"If S should do「もし〜するようなことがあれば」。実現可能性が低いことを表す。"},
    {type:"fill",diff:2,q:"「彼はまるで経済の専門家であるかのように話す」( ___ )を埋めなさい。",
     blank:"He talks as if he ___ an expert in economics.",
     ans:["were"],hint:"as if + 仮定法過去（同時のこと）",
     exp:"as if＋仮定法過去「まるで〜であるかのように」（主節と同時）。"},
    {type:"fill",diff:2,q:"「あなたはまるで幽霊を見たかのような顔をしている」( ___ )を埋めなさい。",
     blank:"You look as if you ___ a ghost.",
     ans:["had seen"],hint:"as if + 仮定法過去完了（以前のこと）",
     exp:"as if＋仮定法過去完了「まるで〜であったかのように」（主節より前）。"},
    {type:"sort",diff:2,q:"ifを省略した倒置文に並べ替えなさい。「（もし）私があなたなら、彼女にデートを申し込むのに」",
     words:["Were","I","you","I","would","ask","her","for","a","date"],
     ans:"Were I you I would ask her for a date",
     exp:"Were I you...（倒置）＝ If I were you,..."},
    {type:"sort",diff:3,q:"「あなたが入院しているとわかっていたら、お見舞いに行ったのに」（ifの省略形）に並べ替えなさい。",
     words:["Had","we","known","you","were","in","the","hospital","we","would","have","visited","you"],
     ans:"Had we known you were in the hospital we would have visited you",
     exp:"Had we known...（倒置）＝ If we had known..."},
    {type:"write",diff:2,q:"「彼女がここにいてくれればなあ！」を I wish を使って英語にしなさい。",
     hint:"If only / I wish + 仮定法過去",
     model:"I wish she were here! / If only she were here!",
     exp:"I wish／If only＋仮定法過去（現在の願望）。"},
    {type:"write",diff:3,q:"「もし宝くじが当たったら、何をしますか？」をwere toを使って英語にしなさい。",
     hint:"If you were to win the lottery ...",
     model:"If you were to win the lottery, what would you do?",
     exp:"〈if S were to＋不定詞〉未来の仮定。"},
    {type:"twist",diff:3,q:"「私は数学が苦手だ（現在の事実）。だから数学のテストが心配だ。」→「もし数学が得意なら、テストが心配でないのに」を仮定法過去で英語にしなさい。",
     hint:"If I were good at math, I wouldn't ...",
     model:"If I were good at math, I wouldn't be worried about the math test.",
     exp:"仮定法過去：現在の事実と反対。"},
    {type:"twist",diff:3,q:"「地震が起きたら、この本棚は前に倒れるだろう」をShould...の倒置形で英語にしなさい。",
     hint:"Should there be an earthquake ...",
     model:"Should there be an earthquake, this bookshelf would fall forward.",
     exp:"if S should doのifを省略した倒置形：Should＋S＋..."},
  ],
  l30:[
    {type:"mc",diff:1,q:"「〜がなければ」（if節の代わり）として使える表現は？",blank:"___ dreams, life would have no meaning.",
     opts:["But for","Without","Both A and B","Except for"],ans:2,
     exp:"but for〜 / without〜「〜がなければ/がなかったら」どちらも正しい。"},
    {type:"mc",diff:2,q:"「音楽がなければ、人生は退屈だろう」正しい表現は？",blank:"",
     opts:["If it were not for music, life would be boring.","If it is not for music, life would be boring.","Were it not for music, life will be boring.","If there were no music, life is boring."],ans:0,
     exp:"〈if it were not for〜〉「もし〜がなければ」（現在）。"},
    {type:"mc",diff:2,q:"「もう〜してもよいころだ」を表す表現は？",blank:"",
     opts:["It's time + 仮定法過去","It's time + 仮定法過去完了","It's time + to不定詞のみ","It's time + 原形"],ans:0,
     exp:"〈it's time＋仮定法過去〉「もう〜してもよいころだ」"},
    {type:"mc",diff:3,q:"「if it had not been for〜」の倒置形は？",blank:"",
     opts:["Had it not been for〜","Were it not for〜","Should it not be for〜","Had not it been for〜"],ans:0,
     exp:"Had it not been for〜（過去の仮定の倒置形）。現在ならWere it not for〜。"},
    {type:"fill",diff:1,q:"「彼女の助言を聞いていさえすれば（よかったのに）なあ！」( ___ )を埋めなさい。",
     blank:"If ___ I had taken her advice!",
     ans:["only"],hint:"if only + 仮定法",
     exp:"〈if only＋仮定法過去完了〉「〜してさえいれば（よかったのに）なあ」"},
    {type:"fill",diff:2,q:"「そうでなければ彼を助けようとしないだろう」( ___ )を埋めなさい。",
     blank:"I know he is innocent; ___ I wouldn't try to save him.",
     ans:["otherwise"],hint:"「そうでなければ」＝if節の代わり",
     exp:"otherwise「そうでなければ」はif節の代わりになる。"},
    {type:"sort",diff:2,q:"「もし〜がなかったら（過去）、私は死んでいたろう」になるよう並べ替えなさい。",
     words:["If","it","had","not","been","for","my","seat","belt","I","would","have","been","killed"],
     ans:"If it had not been for my seat belt I would have been killed",
     exp:"〈if it had not been for〜〉「もし〜がなかったら」（過去）"},
    {type:"sort",diff:3,q:"「もう新しい自転車を買ってもよいころだ」になるよう並べ替えなさい。",
     words:["It's","time","you","bought","a","new","bicycle"],
     ans:"It's time you bought a new bicycle",
     exp:"〈it's time＋仮定法過去〉"},
    {type:"write",diff:2,q:"「お電話をお借りできないかと思いまして」（非常にていねいな依頼）を英語にしなさい。",
     hint:"I was wondering if you could ...",
     model:"I was wondering if you could use your phone.",
     exp:"〈I was wondering if you could〜〉wonderを過去進行形にするとさらにていねい。"},
    {type:"write",diff:3,q:"「夢がなければ、人生に意味はないだろう」をbut for・without・if節の3通りで英語にしなさい。",
     hint:"But for / Without / If it were not for",
     model:"But for dreams, life would have no meaning. / Without dreams, life would have no meaning. / If it were not for dreams, life would have no meaning.",
     exp:"if節に相当する3つの表現。"},
    {type:"twist",diff:3,q:"「友達がいなければ、私は今とても孤独だろう」をif it were not forを使って英語にしなさい。",
     hint:"If it were not for my friends ...",
     model:"If it were not for my friends, I would be very lonely now.",
     exp:"〈if it were not for〜〉「もし〜がなければ」（現在）"},
    {type:"twist",diff:3,q:"【ひねり】「彼は私に窓を開けてもいいか尋ねた（ていねいに）」をwould mindを使って英語にしなさい。",
     hint:"Would you mind if I ...",
     model:"He asked if I would mind if he opened the window. / \"Would you mind if I opened the window?\" he asked.",
     exp:"仮定法を使ったていねいな許可の求め方。Would you mind if I＋仮定法過去？"},
  ],
};

// ============================================================
// EXAM CONFIG
// ============================================================
const EXAM_CONFIG = {
  vocab_count: 1,     // 英単語 1問×15点
  mc_count: 2,        // 四択 2問×10点
  fill_count: 2,      // 穴埋め 2問×10点
  sort_count: 3,      // 並び替え 3問×5点
  write_count: 3,     // ライティング 3問×5点
  twist_count: 3,     // ひねり 3問×5点
  vocab_pts: 15,
  mc_pts: 10,
  fill_pts: 10,
  sort_pts: 5,
  write_pts: 5,
  twist_pts: 5,
  total: 15+20+20+15+15+15  // = 100点
};
